name: Send OneSignal Notifications

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run script
        run: node sendNotification.js
        env:
          ONESIGNAL_API_KEY: ${{ secrets.ONESIGNAL_API_KEY }}
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}

      - name: Commit and push last_sent.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add last_sent.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update last sent video"
            git push origin HEAD:${{ github.ref_name }}
          fi
