name: Send OneSignal Notifications

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Run notification script
        run: node sendNotification.js
        env:
          ONESIGNAL_API_KEY: ${{ secrets.ONESIGNAL_API_KEY }}
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}

      - name: Commit last_sent.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add last_sent.json || true
          git commit -m "Update last sent video" || true
          git push || true
